#
# Jekyll configuration
#
#server: true
destination: ./_site
auto:        false
#server_port: 4000
permalink:   pretty
#paginate:    20
lsi:         false
#lsi:         false
pygments:    true
#markdown:    maruku
markdown:    rdiscount

#
# Site configuration
#
url:          http://www.erickguevara.me
title:        "A Whit of my Internets..."
description:  Living, Experiencing and Computing
author:       Erick I. Guevara # atom.xml: Name of website's author
media_version: 9
media_server: "http://localhost:4000" #http://www.erickguevara.me"