#
# Jekyll configuration
#
#server: true
destination: ./_site
auto:        false
#server_port: 4000
permalink:   pretty
#paginate:    20
lsi:         false
#lsi:         false
pygments:    true
#markdown:    maruku
markdown:    rdiscount

#
# Site configuration
#
url:          http://www.erickguevara.me
title:        "Erick Guevara: A Whit of the Internets..."
description:  My Strategeery Approach to Nada
author:       Erick I. Guevara # atom.xml: Name of website's author
media_version: 9
media_server: "http://www.erickguevara.me"